#!/bin/bash
# =============================================================================
# wz-fw.sh — firewall / routing for web_zapret2
#
#   start      - render firewall for the active EXIT_MODE (idempotent)
#   stop       - remove all web_zapret2 firewall rules
#   status     - show current rules and routing policy
#
# Model: the container is a transparent gateway. Everything generated by the
# access layer (uid "proxy") is desynced by nfqws via NFQUEUE in mangle/OUTPUT.
#   direct    - NFQ on access-uid traffic to NFQ_TCP_PORTS / NFQ_UDP_PORTS
#   socks5/ss - TCP: REDIRECT access-uid traffic into redsocks (SO_ORIGINAL_DST)
#               UDP: policy-route access-uid traffic into utun -> wz-udprelay
#               Exit flows (uid "exituser") to the upstream endpoint get NFQ'd
#               so the tunnel itself is desynced (that is the point of local DPI).
# =============================================================================
set -u
. /opt/webzapret/scripts/wz-common.sh

MODE="$(active_exit_mode)"
EXIT_MODE=$MODE          # make computed upstream endpoints follow the state
compute_upstream
UID_PROXY=$(id -u proxy 2>/dev/null || echo 1001)
UID_EXIT=$(id -u exituser 2>/dev/null || echo 1002)

# ---------------------------------------------------------------------------
fw_flush()
{
    log_module fw "flushing firewall chains and policy routing"
    # remove our chain references
    $IPT -t mangle -D OUTPUT -j WZFW 2>/dev/null || true
    $IPT -t mangle -D PREROUTING -j NFQIN 2>/dev/null || true
    $IPT -t nat     -D OUTPUT -j WZREDIR 2>/dev/null || true
    # flush + delete chains
    $IPT -t mangle -F WZFW 2>/dev/null || true
    $IPT -t mangle -X WZFW 2>/dev/null || true
    $IPT -t mangle -F NFQIN 2>/dev/null || true
    $IPT -t mangle -X NFQIN 2>/dev/null || true
    $IPT -t nat     -F WZREDIR 2>/dev/null || true
    $IPT -t nat     -X WZREDIR 2>/dev/null || true
    # remove policy routing (both the scoped and any pre-scoping variant)
    $IP rule del from all uidrange $UID_PROXY-$UID_PROXY ipproto udp lookup $RT_TABLE_UDP 2>/dev/null || true
    $IP rule del from all uidrange $UID_PROXY-$UID_PROXY lookup $RT_TABLE_UDP 2>/dev/null || true
    $IP route del default dev $UTUN table $RT_TABLE_UDP 2>/dev/null || true
    $IP route flush cache 2>/dev/null || true
}

# add NFQUEUE rule. $1 uid, $2 proto, $3 ports, $4 queue, $5 pktlim
nfq_rule()
{
    local uid=$1 proto=$2 ports=$3 qnum=$4 pktlim=$5
    [ "$(active_strategy)" = none ] && return 0
    qnum=$QNUM_TCP
    if [ -n "$pktlim" ] && [ "$pktlim" -gt 0 ] 2>/dev/null; then
        $IPT -t mangle -A WZFW -p "$proto" -m owner --uid-owner "$uid" \
            -m multiport --dports "$ports" \
            -m mark ! --mark $DESYNC_MARK/$DESYNC_MARK \
            -m connbytes --connbytes-dir original --connbytes-mode packets \
            --connbytes 1:$pktlim \
            -j NFQUEUE --queue-num "$qnum" --queue-bypass
    else
        $IPT -t mangle -A WZFW -p "$proto" -m owner --uid-owner "$uid" \
            -m multiport --dports "$ports" \
            -m mark ! --mark $DESYNC_MARK/$DESYNC_MARK \
            -j NFQUEUE --queue-num "$qnum" --queue-bypass
    fi
}

fw_apply()
{
    log_module fw "applying firewall for exit mode '$MODE' (ports: tcp=$NFQ_TCP_PORTS, udp=$NFQ_UDP_PORTS)"
    mkdir -p "$WZ_RUN"

    # ---- mangle/WZFW: our own chain, hooked into OUTPUT ----
    $IPT -t mangle -N WZFW 2>/dev/null || $IPT -t mangle -F WZFW
    if ! $IPT -t mangle -C OUTPUT -j WZFW 2>/dev/null; then
        $IPT -t mangle -I OUTPUT -j WZFW
    fi
    # guards: never divert nfqws re-injected packets or loopback
    $IPT -t mangle -I WZFW 1 -m mark --mark $DESYNC_MARK/$DESYNC_MARK -j RETURN
    $IPT -t mangle -I WZFW 2 -o lo -j RETURN

    case "$MODE" in
        direct)
            nfq_rule "$UID_PROXY" tcp "$NFQ_TCP_PORTS" "$QNUM_TCP" "$NFQWS_TCP_PKT_OUT"
            nfq_rule "$UID_PROXY" udp "$NFQ_UDP_PORTS" "$QNUM_UDP" "$NFQWS_UDP_PKT_OUT"
            ;;

        socks5|ss)
            # ---- TCP: access layer -> redsocks (original dst via SO_ORIGINAL_DST)
            $IPT -t nat -N WZREDIR 2>/dev/null || $IPT -t nat -F WZREDIR
            if ! $IPT -t nat -C OUTPUT -j WZREDIR 2>/dev/null; then
                $IPT -t nat -I OUTPUT -j WZREDIR
            fi
            $IPT -t nat -A WZREDIR -p tcp -m owner --uid-owner "$UID_PROXY" \
                -j REDIRECT --to-ports "$REDSOCKS_PORT"

            # ---- UDP: access layer -> utun (relay reads original dst from IP header)
            # policy route is scoped TWICE: by uid (only ss-server/sockd, i.e.
            # datagrams decrypted from OUR clients) and by ipproto udp. Other
            # container UDP (panel, nfqws, DNS of other uids) is untouched.
            if [ "$UDP_PROXY" = relay ]; then
                $IP rule add from all uidrange $UID_PROXY-$UID_PROXY ipproto udp lookup $RT_TABLE_UDP 2>/dev/null
                $IP route add default dev "$UTUN" table $RT_TABLE_UDP 2>/dev/null
                $IP link set "$UTUN" up 2>/dev/null || true
                $IP route flush cache 2>/dev/null || true
            else
                nfq_rule "$UID_PROXY" udp "$NFQ_UDP_PORTS" "$QNUM_UDP" "$NFQWS_UDP_PKT_OUT"
            fi

            # ---- desync of exit flows (redsocks/ss-local/udprelay -> upstream)
            [ -n "$UP_TCP_PORT" ] && nfq_rule "$UID_EXIT" tcp "$UP_TCP_PORT" "$QNUM_TCP" "$NFQWS_TCP_PKT_OUT"
            [ -n "$UP_UDP_PORT" ] && nfq_rule "$UID_EXIT" udp "$UP_UDP_PORT" "$QNUM_UDP" "$NFQWS_UDP_PKT_OUT"
            ;;
    esac

    # ---- ingress counting chain (for traffic counter) ----
    # Count bytes of incoming packets in PREROUTING.  The RETURN rule at the
    # end of NFQIN matches every packet, so its byte counter is the total
    # ingress byte count.  Reset only on firewall reload (exit-mode change).
    $IPT -t mangle -N NFQIN 2>/dev/null || $IPT -t mangle -F NFQIN
    $IPT -t mangle -D PREROUTING -j NFQIN 2>/dev/null || true
    $IPT -t mangle -I PREROUTING 1 -j NFQIN
    $IPT -t mangle -A NFQIN -j RETURN
}

fw_status()
{
    echo "== exit mode: $MODE (state: $(cat "$WZ_STATE/exit_mode" 2>/dev/null || echo none))"
    echo; echo "== mangle OUTPUT =="
    $IPT -t mangle -S OUTPUT
    echo; echo "== mangle WZFW =="
    $IPT -t mangle -S WZFW
    echo; echo "== nat OUTPUT =="
    $IPT -t nat -S OUTPUT
    echo; echo "== routing policy =="
    $IP rule show
    echo; echo "== routing table $RT_TABLE_UDP =="
    $IP route show table "$RT_TABLE_UDP" 2>/dev/null || true
}

case "${1:-}" in
    start)  fw_apply ;;
    stop)   fw_flush ;;
    status) fw_status ;;
    *) echo "usage: $0 {start|stop|status}" >&2; exit 1 ;;
esac
exit 0
